### ISSUE TITLE
just a heads up

### ISSUE THREAD

**Issue by franzenzenhofer** [michaelbromley/chromata#1]
hi, i hard forked chromata 
https://github.com/franzenzenhofer/chromata-effects
to play around with it in some way.

also i got rid of gulp and stuff and now use babbel and webpack to package it as I could not rebuild the original on my mac. 

if my changes produce something useful i will try to create a sane push request. 

lg
franz

**Comment by michaelbromley** [comment]
Cool - yeah I built this in the days before I knew about Webpack and when Babel was still "6to5"!

Have fun!
